(define (Egg.Expr? v)
  (or (Egg.Expr.Lambda? v)
      (Egg.Expr.Binop? v)
      (Egg.Expr.App? v)
      (Egg.Expr.Var? v)
      (Egg.Expr.Int? v)))


(define (Egg.Expr.Lambda parameter body)
  (unless (Egg.Expr.Var? parameter)
    (error 'Egg.Expr.Lambda "Parameter must be an Egg.Expr" parameter))
  (unless (Egg.Expr? body)
    (error 'Egg.Expr.Lambda "Body must be an Egg.Expr" body))
  (pipe (Egg.Object 'Egg.Expr.Lambda)
	(curry Egg.Object.set ':parameter parameter)
	(curry Egg.Object.set ':body body)))
(define (Egg.Expr.Lambda? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Expr.Lambda)))

(define (Egg.Expr.Lambda.getParameter e)
  (unless (Egg.Expr.Lambda? e)
    (error 'Egg.Expr.Lambda.getParameter "Not an Egg.Expr.Lambda" e))
  (Egg.Object.get ':parameter #f e))
(define (Egg.Expr.Lambda.setParameter parameter e)
  (unless (Egg.Expr.Lambda? e)
    (error 'Egg.Expr.Lambda.setParameter "Not an Egg.Expr.Lambda" e))
  (unless (Egg.Expr.Var? parameter)
    (error 'Egg.Expr.Lambda.setParameter "Parameter must be an Egg.Expr.Var" parameter))
  (Egg.Object.set ':parameter parameter e))

(define (Egg.Expr.Lambda.getBody e)
  (unless (Egg.Expr.Lambda? e)
    (error 'Egg.Expr.Lambda.getBody "Not an Egg.Expr.Lambda" e))
  (Egg.Object.get ':body #f e))
(define (Egg.Expr.Lambda.setBody body e)
  (unless (Egg.Expr.Lambda? e)
    (error 'Egg.Expr.Lambda.setBody "Not an Egg.Expr.Lambda" e))
  (unless (Egg.Expr? body)
    (error 'Egg.Expr.Lambda.setBody "Body must be an Egg.Expr" body))
  (Egg.Object.set ':body body e))


(define Egg.Expr.Binop.OPS (list 'Add 'Mul))

(define (Egg.Expr.Binop op lhs rhs)
  (unless (in op Egg.Expr.Binop.OPS)
    (error 'Egg.Expr.Binop "Op must be in ops" op Egg.Expr.Binop.OPS))
  (unless (Egg.Expr? lhs)
    (error 'Egg.Expr.Binop "Lhs must be an Egg.Expr" lhs))
  (unless (Egg.Expr? rhs)
    (error 'Egg.Expr.Binop "Rhs must be an Egg.Expr" rhs))
  (pipe (Egg.Object 'Egg.Expr.Binop)
	(curry Egg.Object.set ':op op)
	(curry Egg.Object.set ':lhs lhs)
	(curry Egg.Object.set ':rhs rhs)))
(define (Egg.Expr.Binop? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Expr.Binop)))

(define (Egg.Expr.Binop.getOp e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.getOp "Not an Egg.Expr.Binop" e))
  (Egg.Object.get ':op #f e))
(define (Egg.Expr.Binop.setOp op e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.setOp "Not an Egg.Expr.Binop" e))
  (unless (in op Egg.Expr.Binop.OPS)
    (error 'Egg.Expr.Binop.setOp "Op must be in ops" op Egg.Expr.Binop.OPS))
  (Egg.Object.set ':op op e))

(define (Egg.Expr.Binop.getLhs e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.getLhs "Not an Egg.Expr.Binop" e))
  (Egg.Object.get ':lhs #f e))
(define (Egg.Expr.Binop.setLhs lhs e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.setLhs "Not an Egg.Expr.Binop" e))
  (unless (Egg.Expr? lhs)
    (error 'Egg.Expr.Binop.setLhs "Lhs must be an Egg.Expr" lhs))
  (Egg.Object.set ':lhs lhs e))

(define (Egg.Expr.Binop.getRhs e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.getRhs "Not an Egg.Expr.Binop" e))
  (Egg.Object.get ':rhs #f e))
(define (Egg.Expr.Binop.setRhs rhs e)
  (unless (Egg.Expr.Binop? e)
    (error 'Egg.Expr.Binop.setRhs "Not an Egg.Expr.Binop" e))
  (unless (Egg.Expr? rhs)
    (error 'Egg.Expr.Binop.setRhs "Rhs must be an Egg.Expr" rhs))
  (Egg.Object.set ':rhs rhs e))


(define (Egg.Expr.App lhs rhs)
  (unless (Egg.Expr? lhs)
    (error 'Egg.Expr.App "Lhs must be an Egg.Expr" lhs))
  (unless (Egg.Expr? rhs)
    (error 'Egg.Expr.App "Rhs must be an Egg.Expr" rhs))
  (pipe (Egg.Object 'Egg.Expr.App)
	(curry Egg.Object.set ':lhs lhs)
	(curry Egg.Object.set ':rhs rhs)))
(define (Egg.Expr.App? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Expr.App)))

(define (Egg.Expr.App.getLhs e)
  (unless (Egg.Expr.App? e)
    (error 'Egg.Expr.App.getLhs "Not an Egg.Expr.App" e))
  (Egg.Object.get ':lhs #f e))
(define (Egg.Expr.App.setLhs lhs e)
  (unless (Egg.Expr.App? e)
    (error 'Egg.Expr.App.setLhs "Not an Egg.Expr.App" e))
  (unless (Egg.Expr? lhs)
    (error 'Egg.Expr.App.setLhs "Lhs must be an Egg.Expr" lhs))
  (Egg.Object.set ':lhs lhs e))

(define (Egg.Expr.App.getRhs e)
  (unless (Egg.Expr.App? e)
    (error 'Egg.Expr.App.getRhs "Not an Egg.Expr.App" e))
  (Egg.Object.get ':rhs #f e))
(define (Egg.Expr.App.setRhs rhs e)
  (unless (Egg.Expr.App? e)
    (error 'Egg.Expr.App.setRhs "Not an Egg.Expr.App" e))
  (unless (Egg.Expr? rhs)
    (error 'Egg.Expr.App.setRhs "Rhs must be an Egg.Expr" rhs))
  (Egg.Object.set ':rhs rhs e))


(define (Egg.Expr.Var name)
  (unless (string? name)
    (error 'Egg.Expr.Var "Name must be a string" name))
  (pipe (Egg.Object 'Egg.Expr.Var)
	(curry Egg.Object.set ':name name)))
(define (Egg.Expr.Var? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Expr.Var)))

(define (Egg.Expr.Var.getName e)
  (unless (Egg.Expr.Var? e)
    (error 'Egg.Expr.Var.getName "Not an Egg.Expr.Var" e))
  (Egg.Object.get ':name #f e))
(define (Egg.Expr.Var.setName name e)
  (unless (Egg.Expr.Var? e)
    (error 'Egg.Expr.Var.setName "Not an Egg.Expr.Var" e))
  (unless (string? name)
    (error 'Egg.Expr.Var.setName "Name must be a string" name))
  (Egg.Object.set ':name name e))


(define (Egg.Expr.Int value)
  (unless (integer? value)
    (error 'Egg.Expr.Int "Value must be an integer" value))
  (pipe (Egg.Object 'Egg.Expr.Int)
	(curry Egg.Object.set ':value value)))
(define (Egg.Expr.Int? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Expr.Int)))

(define (Egg.Expr.Int.getValue e)
  (unless (Egg.Expr.Int? e)
    (error 'Egg.Expr.Int.getValue "Not an Egg.Expr.Int" e))
  (Egg.Object.get ':value #f e))
(define (Egg.Expr.Int.setValue value e)
  (unless (Egg.Expr.Int? e)
    (error 'Egg.Expr.Int.setValue "Not an Egg.Expr.Int" e))
  (unless (integer? value)
    (error 'Egg.Expr.Int.setValue "Value must be an integer" value))
  (Egg.Object.set ':value value e))
