(define (Egg.Token? v)
  (or (Egg.Token.Let? v)
      (Egg.Token.In? v)
      (Egg.Token.Equal? v)
      (Egg.Token.Plus? v)
      (Egg.Token.Star? v)
      (Egg.Token.Dot? v)
      (Egg.Token.LP? v)
      (Egg.Token.RP? v)
      (Egg.Token.Int? v)
      (Egg.Token.Id? v)
      (Egg.Token.Lambda? v)
      (Egg.Token.Unknown? v)))


(define (Egg.Token.Let)
  (Egg.Object 'Egg.Token.Let))
(define (Egg.Token.Let? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Let)))


(define (Egg.Token.In)
  (Egg.Object 'Egg.Token.In))
(define (Egg.Token.In? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.In)))


(define (Egg.Token.Equal)
  (Egg.Object 'Egg.Token.Equal))
(define (Egg.Token.Equal? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Equal)))


(define (Egg.Token.Plus)
  (Egg.Object 'Egg.Token.Plus))
(define (Egg.Token.Plus? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Plus)))


(define (Egg.Token.Star)
  (Egg.Object 'Egg.Token.Star))
(define (Egg.Token.Star? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Star)))


(define (Egg.Token.Dot)
  (Egg.Object 'Egg.Token.Dot))
(define (Egg.Token.Dot? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Dot)))


(define (Egg.Token.LP)
  (Egg.Object 'Egg.Token.LP))
(define (Egg.Token.LP? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.LP)))


(define (Egg.Token.RP)
  (Egg.Object 'Egg.Token.RP))
(define (Egg.Token.RP? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.RP)))


(define (Egg.Token.Int value)
  (unless (integer? value)
    (error 'Egg.Token.Int "Value must be an integer" value))
  (pipe (Egg.Object 'Egg.Token.Int)
	(curry Egg.Object.set ':value value)))
(define (Egg.Token.Int? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Int)))

(define (Egg.Token.Int.getValue t)
  (unless (Egg.Token.Int? t)
    (error 'Egg.Token.Int.getValue "Not an Egg.Token.Int" t))
  (Egg.Object.get ':value #f t))
(define (Egg.Token.Int.setValue value t)
  (unless (Egg.Token.Int? t)
    (error 'Egg.Token.Int.setValue "Not an Egg.Token.Int" t))
  (unless (integer? value)
    (error 'Egg.Token.Int.setValue "Value must be an integer" value))
  (Egg.Object.set ':value value t))


(define (Egg.Token.Id name)
  (unless (string? name)
    (error 'Egg.Token.Id "Name must be a string" name))
  (pipe (Egg.Object 'Egg.Token.Id)
	(curry Egg.Object.set ':name name)))
(define (Egg.Token.Id? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Id)))

(define (Egg.Token.Id.getName t)
  (unless (Egg.Token.Id? t)
    (error 'Egg.Token.Id.getName "Not an Egg.Token.Id" t))
  (Egg.Object.get ':name #f t))
(define (Egg.Token.Id.setName name t)
  (unless (Egg.Token.Id? t)
    (error 'Egg.Token.Id.setName "Not an Egg.Token.Id" t))
  (unless (string? name)
    (error 'Egg.Token.Id.setName "Name must be a string" name))
  (Egg.Object.set ':name name t))


(define (Egg.Token.Lambda parameter)
  (unless (string? parameter)
    (error 'Egg.Token.Lambda "Parameter must be a string" parameter))
  (pipe (Egg.Object 'Egg.Token.Lambda)
	(curry Egg.Object.set ':parameter parameter)))
(define (Egg.Token.Lambda? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Lambda)))

(define (Egg.Token.Lambda.getParameter t)
  (unless (Egg.Token.Lambda? t)
    (error 'Egg.Token.Lambda.getParameter "Not an Egg.Token.Lambda" t))
  (Egg.Object.get ':parameter #f t))
(define (Egg.Token.Lambda.setParameter parameter t)
  (unless (Egg.Token.Lambda? t)
    (error 'Egg.Token.Lambda.setParameter "Not an Egg.Token.Lambda" t))
  (unless (string? parameter)
    (error 'Egg.Token.Lambda.setParameter "Parameter must be a string" parameter))
  (Egg.Object.set ':parameter parameter t))


(define (Egg.Token.Unknown char)
  (unless (char? char)
    (error 'Egg.Token.Unknown "Char must be a char" char))
  (pipe (Egg.Object 'Egg.Token.Unknown)
	(curry Egg.Object.set ':char char)))
(define (Egg.Token.Unknown? v)
  (and (Egg.Object? v)
       (equal? (Egg.Object.getTag v)
	       'Egg.Token.Unknown)))

(define (Egg.Token.Unknown.getChar t)
  (unless (Egg.Token.Unknown? t)
    (error 'Egg.Token.Unknown.getChar "Not an Egg.Token.Unknown" t))
  (Egg.Object.get ':char #f t))
(define (Egg.Token.Unknown.setChar char t)
  (unless (Egg.Token.Unknown? t)
    (error 'Egg.Token.Unknown.setChar "Not an Egg.Token.Unknown" t))
  (unless (char? char)
    (error 'Egg.Token.Unknown.setChar "Char must be a char" char))
  (Egg.Object.set ':char char t))
